-- 清理所有表的重复索引（只保留第一个）
USE art_auction;

SET FOREIGN_KEY_CHECKS = 0;

-- categories 表：删除 slug_2 ~ slug_63
DROP INDEX slug_2 ON categories;
DROP INDEX slug_3 ON categories;
DROP INDEX slug_4 ON categories;
DROP INDEX slug_5 ON categories;
DROP INDEX slug_6 ON categories;
DROP INDEX slug_7 ON categories;
DROP INDEX slug_8 ON categories;
DROP INDEX slug_9 ON categories;
DROP INDEX slug_10 ON categories;
DROP INDEX slug_11 ON categories;
DROP INDEX slug_12 ON categories;
DROP INDEX slug_13 ON categories;
DROP INDEX slug_14 ON categories;
DROP INDEX slug_15 ON categories;
DROP INDEX slug_16 ON categories;
DROP INDEX slug_17 ON categories;
DROP INDEX slug_18 ON categories;
DROP INDEX slug_19 ON categories;
DROP INDEX slug_20 ON categories;
DROP INDEX slug_21 ON categories;
DROP INDEX slug_22 ON categories;
DROP INDEX slug_23 ON categories;
DROP INDEX slug_24 ON categories;
DROP INDEX slug_25 ON categories;
DROP INDEX slug_26 ON categories;
DROP INDEX slug_27 ON categories;
DROP INDEX slug_28 ON categories;
DROP INDEX slug_29 ON categories;
DROP INDEX slug_30 ON categories;
DROP INDEX slug_31 ON categories;
DROP INDEX slug_32 ON categories;
DROP INDEX slug_33 ON categories;
DROP INDEX slug_34 ON categories;
DROP INDEX slug_35 ON categories;
DROP INDEX slug_36 ON categories;
DROP INDEX slug_37 ON categories;
DROP INDEX slug_38 ON categories;
DROP INDEX slug_39 ON categories;
DROP INDEX slug_40 ON categories;
DROP INDEX slug_41 ON categories;
DROP INDEX slug_42 ON categories;
DROP INDEX slug_43 ON categories;
DROP INDEX slug_44 ON categories;
DROP INDEX slug_45 ON categories;
DROP INDEX slug_46 ON categories;
DROP INDEX slug_47 ON categories;
DROP INDEX slug_48 ON categories;
DROP INDEX slug_49 ON categories;
DROP INDEX slug_50 ON categories;
DROP INDEX slug_51 ON categories;
DROP INDEX slug_52 ON categories;
DROP INDEX slug_53 ON categories;
DROP INDEX slug_54 ON categories;
DROP INDEX slug_55 ON categories;
DROP INDEX slug_56 ON categories;
DROP INDEX slug_57 ON categories;
DROP INDEX slug_58 ON categories;
DROP INDEX slug_59 ON categories;
DROP INDEX slug_60 ON categories;
DROP INDEX slug_61 ON categories;
DROP INDEX slug_62 ON categories;
DROP INDEX slug_63 ON categories;

-- auctions 表：删除 auction_id_2 ~ auction_id_58 和 auctions_auction_id
DROP INDEX auctions_auction_id ON auctions;
DROP INDEX auction_id_2 ON auctions;
DROP INDEX auction_id_3 ON auctions;
DROP INDEX auction_id_4 ON auctions;
DROP INDEX auction_id_5 ON auctions;
DROP INDEX auction_id_6 ON auctions;
DROP INDEX auction_id_7 ON auctions;
DROP INDEX auction_id_8 ON auctions;
DROP INDEX auction_id_9 ON auctions;
DROP INDEX auction_id_10 ON auctions;
DROP INDEX auction_id_11 ON auctions;
DROP INDEX auction_id_12 ON auctions;
DROP INDEX auction_id_13 ON auctions;
DROP INDEX auction_id_14 ON auctions;
DROP INDEX auction_id_15 ON auctions;
DROP INDEX auction_id_16 ON auctions;
DROP INDEX auction_id_17 ON auctions;
DROP INDEX auction_id_18 ON auctions;
DROP INDEX auction_id_19 ON auctions;
DROP INDEX auction_id_20 ON auctions;
DROP INDEX auction_id_21 ON auctions;
DROP INDEX auction_id_22 ON auctions;
DROP INDEX auction_id_23 ON auctions;
DROP INDEX auction_id_24 ON auctions;
DROP INDEX auction_id_25 ON auctions;
DROP INDEX auction_id_26 ON auctions;
DROP INDEX auction_id_27 ON auctions;
DROP INDEX auction_id_28 ON auctions;
DROP INDEX auction_id_29 ON auctions;
DROP INDEX auction_id_30 ON auctions;
DROP INDEX auction_id_31 ON auctions;
DROP INDEX auction_id_32 ON auctions;
DROP INDEX auction_id_33 ON auctions;
DROP INDEX auction_id_34 ON auctions;
DROP INDEX auction_id_35 ON auctions;
DROP INDEX auction_id_36 ON auctions;
DROP INDEX auction_id_37 ON auctions;
DROP INDEX auction_id_38 ON auctions;
DROP INDEX auction_id_39 ON auctions;
DROP INDEX auction_id_40 ON auctions;
DROP INDEX auction_id_41 ON auctions;
DROP INDEX auction_id_42 ON auctions;
DROP INDEX auction_id_43 ON auctions;
DROP INDEX auction_id_44 ON auctions;
DROP INDEX auction_id_45 ON auctions;
DROP INDEX auction_id_46 ON auctions;
DROP INDEX auction_id_47 ON auctions;
DROP INDEX auction_id_48 ON auctions;
DROP INDEX auction_id_49 ON auctions;
DROP INDEX auction_id_50 ON auctions;
DROP INDEX auction_id_51 ON auctions;
DROP INDEX auction_id_52 ON auctions;
DROP INDEX auction_id_53 ON auctions;
DROP INDEX auction_id_54 ON auctions;
DROP INDEX auction_id_55 ON auctions;
DROP INDEX auction_id_56 ON auctions;
DROP INDEX auction_id_57 ON auctions;
DROP INDEX auction_id_58 ON auctions;

SET FOREIGN_KEY_CHECKS = 1;

-- 验证结果
SELECT TABLE_NAME, COUNT(*) AS index_count FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = 'art_auction' GROUP BY TABLE_NAME ORDER BY index_count DESC;
